baseURL = "https://accessa.ch"
title = "ACCESSA"
author = "ACCESSA GmbH"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google nnnalytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.jpg"
    alt = "ACCESSA Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-16"

  [params.site]
    name = "ACCESSA GmbH"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Company website for ACCESSA GmbH"
    meta_og_title = "ACCESSA"
    meta_og_type = "website"
    meta_og_url = "https://accessa.ch"
    meta_og_image = "./images/tn.png"
    meta_og_description = "Company website for ACCESSA GmbH"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@alxstai"
    meta_twitter_creator = "@alxstai"

[menu]

  [[menu.main]]
    identifier = "expertise"
    name = "Expertise"
    url = "/#expertise"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "javascript:void(0);"  # Changed to "#" so clicking "About" doesn't navigate away
    weight = 3
  
  [[menu.main]]
    name = "About Us"
    url = "/about-us" 
    parent = "about"
    weight = 1

  [[menu.main]]
    name = "Our Team"
    url = "/team"
    parent = "about"
    weight = 2
    
  [[menu.main]]
    identifier = "core"
    name = "Core Areas"
    url = "/core"
    weight = 2
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Imprint"
    url = "/imprint"
    weight = 2

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy"
    weight = 3

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/accessaconsulting"
    pre = "<i class='fab fa-linkedin text-2xl'></i>"
      weight = 4

  [[menu.footer]]
    name = "Email"
    url = "mailto:info@accessa.ch"
    pre = "<i class='fas fa-envelope text-2xl'></i>"
      weight = 5
