baseURL = "https://example.com"
title = "Tella"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Uncomment the following line if the site is available in Japanese, Chinese, or Korean.
#hasCJKLanguage = true

# Uncomment and replace with your Google Analytics tracking ID to enable Google Analytics.
#googleAnalytics = "UA-12345678-1"

# Uncomment and set your Disqus shortname to enable Disqus Comment System.
#disqusShortname = ""

[params]
  showBlog = true
  mainSections = ['blog']
  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Tella Logo"
    # The size parameter is the class name of tailwindcss
    size = "h-14"

  [params.site]
    name = "Tella"

  [params.icon]
    # Set this parameter to true to use FontAwesome.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSS Project, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSS Project, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
    weight = 2